-- ============================================================================
-- 05_cleanup.sql
-- Tears down everything this project created. Safe to run any time to stop
-- consuming credits (e.g. on a trial account).
-- ============================================================================

USE ROLE STREAMING_PIPELINE_ROLE;

DROP STREAMLIT     IF EXISTS STREAMING_PIPELINE_DB.EVENTS.SERVICE_HEALTH_DASHBOARD;
DROP TABLE         IF EXISTS STREAMING_PIPELINE_DB.EVENTS.SERVICE_HEALTH_SERVING;
DROP DYNAMIC TABLE IF EXISTS STREAMING_PIPELINE_DB.EVENTS.GOLD_SERVICE_HEALTH;
DROP DYNAMIC TABLE IF EXISTS STREAMING_PIPELINE_DB.EVENTS.SILVER_SERVICE_EVENTS;
DROP TABLE         IF EXISTS STREAMING_PIPELINE_DB.EVENTS.BRONZE_SERVICE_EVENTS;
DROP SCHEMA        IF EXISTS STREAMING_PIPELINE_DB.EVENTS;
DROP DATABASE      IF EXISTS STREAMING_PIPELINE_DB;
DROP WAREHOUSE     IF EXISTS STREAMING_PIPELINE_WH;

-- Run these last two as ACCOUNTADMIN from a separate session — the role/user
-- above can't drop itself while it's the active connection.
-- USE ROLE ACCOUNTADMIN;
-- DROP USER IF EXISTS STREAMING_PIPELINE_USER;
-- DROP ROLE IF EXISTS STREAMING_PIPELINE_ROLE;
-- DROP NETWORK POLICY IF EXISTS STREAMING_PIPELINE_NP;
